### ISSUE TITLE
chrome で remember-me 認証エラーが発生する。

### ISSUE THREAD

**Issue by live134** [live134/sbb#5]
エラー発生手順
・chrome で remember-me 認証ログイン。
・/login にアクセスしたりする。
・ブラウザを落として、再度アクセス。
・エラー発生。

補足
・たまにエラーが発生しないことがある。
・開発者モードだと良く発生する。 / へのアクセスでもたまに発生していた。
・firefox, ie だと発生しない模様。

エラー詳細
org.springframework.security.web.authentication.rememberme.CookieTheftException: Invalid remember-me token (Series/token) mismatch. Implies previous cookie theft attack.
at org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices.processAutoLoginCookie(PersistentTokenBasedRememberMeServices.java:102)
at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.autoLogin(AbstractRememberMeServices.java:115)

**Comment by live134** [comment]
chrome がバージョンアップされたら発生しなくなった。
確認したバージョンは「43.0.2357.124」。
